name: Github Actions
on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # TODO windows-latest is having issues

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: nimble test -y
    - run: nimble test --gc:orc -y
    - name: Compile Nim code
      run: nim c -d:release src/monoprompt.nim
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: monoprompt-bin
        path: ./src/monoprompt

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: monoprompt-bin
          path: ./src
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: src/monoprompt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}